### ISSUE TITLE
[Feature Request] Move stats a little bit higher when only icons are visible

### ISSUE THREAD

**Issue by forever-and-a-day** [Kiokuu/NameplateStats#10]
When nameplates are set to icon only mode, the stats bar cuts of part of the profile picture. Would be nice if the stats bar was moved a bit higher in this mode.

**Comment by Kiokuu** [comment]
will work on soon

**Comment by Kiokuu** [comment]
Should be fixed by 837f82e , If it remains a issue, reopen the issue.
